version: "3.9"

services:
  backend:
    build: ./backend
    container_name: healthtech-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend/frontend
    container_name: healthtech-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/frontend:/app
    depends_on:
      - backend
    restart: always
